dotenv: .env

wallets:
  from_key: ${PRIVATE_KEY}

subscriptions:
  chainlink: ${CHAINLINK_SUBSCRIPTION_ID}



dependencies:
  # - <organizzation/repo>@<version> scaricate da GitHub
  - smartcontractkit/chainlink-brownie-contracts@0.2.1
  - smartcontractkit/chainlink@1.2.1
  - OpenZeppelin/openzeppelin-contracts@4.5.0
  - aave/protocol-v2@1.0.1

compiler:
  # spiegare al compiler che @chainlink punta alla dipendenza su GitHub
  solc:
    remappings:
      - '@brownie-cl=smartcontractkit/chainlink-brownie-contracts@0.2.1'
      - '@chainlink=smartcontractkit/chainlink@1.2.1'
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.5.0'
      - '@aave=aave/protocol-v2@1.0.1'



networks:
  default: mainnet-fork
  development: 
    keyhash: '0xd89b2bf150e3b9e13446986e571fb9cab24b13cea0a43ea20a6049a85cc807cc'
  mainnet-fork:
    eth_usd_price_feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'
    weth_token: '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2'
    dai_token: '0x6B175474E89094C44Da98b954EedeAC495271d0F'
    lending_pool_addresses_provider: '0xB53C1a33016B2DC2fF3653530bfF1848a515c8c5'
    dai_eth_price_feed: '0x773616E4d11A78F511299002da57A0a94577F1f4'
    verify: False
  rinkeby:
    eth_usd_price_feed: '0x8A753747A1Fa494EC906cE90E9f37563A8AF630e'
    vrf_coordinator: '0x6168499c0cFfCaCD319c818142124B7A15E857ab'
    link_token: '0x01BE23585060835E02B77ef475b0Cc51aA1e0709'
    keyhash: '0xd89b2bf150e3b9e13446986e571fb9cab24b13cea0a43ea20a6049a85cc807cc'
    verify: True
  kovan:
    weth_token: '0xd0A1E359811322d97991E03f863a0C30C2cF029C'
    dai_token: '0xFf795577d9AC8bD7D90Ee22b6C1703490b6512FD'
    lending_pool_addresses_provider: '0x88757f2f99175387aB4C6a4b3067c77A695b0349'
    dai_eth_price_feed: '0x22B58f1EbEDfCA50feF632bD73368b2FdA96D541'
